name: paper_cropper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - opencv=4.8.0
  - numpy=1.24.3
  - matplotlib=3.7.1
  - jupyter=1.0.0
  - pip=23.1.2
  - pip:
    - opencv-contrib-python==4.8.0.76