version: "3.8"

services:
  ml-backend:
    container_name: ml-backend
    image: humansignal/ml-backend:v0
    build: .
    restart: always
    environment:
      # - MODEL_DIR=/data/models
      - MODEL_DIR=/app
      - WORKERS=2
      - THREADS=4
      - LOG_LEVEL=DEBUG
      - ANY=PARAMETER
      - LABEL_STUDIO_HOST=http://label.lucasliu.net
      - LABEL_STUDIO_API_KEY=b7e78c338c72f337a00df7633d81a64138f7eee8
    ports:
      - "9090:9090"
