version: "3.8"

services:
  ml-backend:
    container_name: ml-backend
    image: humansignal/ml-backend:v0
    build: .
    restart: always
    env_file:
      - .env
    environment:
      # - MODEL_DIR=/data/models
      - MODEL_DIR=/app
      - WORKERS=2
      - THREADS=4
      - LOG_LEVEL=DEBUG
      - ANY=PARAMETER
      - LABEL_STUDIO_HOST=http://label.lucasliu.net
    ports:
      - "9090:9090"
